export default {
    ActiveUsers: [
        {
            name: `Anna`,
            profileImage: `https://randomuser.me/api/portraits/women/12.jpg`,
            active: true,
        },
        {
            name: `Jeff`,
            profileImage: `https://randomuser.me/api/portraits/men/75.jpg`,
            active: false,
        },
        {
            name: `Cathy`,
            profileImage: `https://randomuser.me/api/portraits/women/42.jpg`,
            active: true,
        },
        {
            name: `Madona`,
            profileImage: `https://randomuser.me/api/portraits/women/87.jpg`,
            active: false,
        },
        {
            name: `Emma`,
            profileImage: `https://randomuser.me/api/portraits/women/23.jpg`,
            active: false,
        },
        {
            name: `Mark`,
            profileImage: `https://randomuser.me/api/portraits/men/65.jpg`,
            active: true,
        },
        {
            name: `Eva`,
            profileImage: `https://randomuser.me/api/portraits/women/65.jpg`,
            active: true,
        },
        {
            name: `Max`,
            profileImage: `https://randomuser.me/api/portraits/men/31.jpg`,
            active: true,
        },
        {
            name: `Adam`,
            profileImage: `https://randomuser.me/api/portraits/men/81.jpg`,
            active: true,
        },
    ],
    Contacts: [
        {
            profileImage: `https://randomuser.me/api/portraits/women/61.jpg`,
            name: `Angelina Jolie`,
            message: `Ok, see you at the subway in a bit.`,
            time: `Just now`,
            now: false,
            select: false,
        },
        {
            profileImage: `https://randomuser.me/api/portraits/men/97.jpg`,
            name: `Tony Stark`,
            message: `Hey, Are you there?`,
            time: `10min`,
            now: true,
            select: false,
        },
        {
            profileImage: `https://randomuser.me/api/portraits/women/33.jpg`,
            name: `Scarlett Johansson`,
            message: `You sent a photo.`,
            time: `1h`,
            now: false,
            select: true,
        },
        {
            profileImage: `https://randomuser.me/api/portraits/men/12.jpg`,
            name: `John Snow`,
            message: `You missed a call John.`,
            time: `4h`,
            now: false,
            select: false,
        },
        {
            profileImage: `https://randomuser.me/api/portraits/women/23.jpg`,
            name: `Emma Watson`,
            message: `You sent a video.`,
            time: `11 Feb`,
            now: false,
            select: false,
        },
        {
            profileImage: `https://randomuser.me/api/portraits/women/87.jpg`,
            name: `Sunny Leone`,
            message: `Ah, it was an awesome one night stand.`,
            time: `1 Feb`,
            now: false,
            select: false,
        },
        {
            profileImage: `https://randomuser.me/api/portraits/men/45.jpg`,
            name: `Bruce Lee`,
            message: `You are a great human being.`,
            time: `23 Jan`,
            now: false,
            select: false,
        },
        {
            profileImage: `https://randomuser.me/api/portraits/men/55.jpg`,
            name: `TailwindCSS Group`,
            message: `Adam: Hurray, Version 2 is out now!!.`,
            time: `23 Jan`,
            now: false,
            select: false,
        },
        {
            profileImage: `https://randomuser.me/api/portraits/men/34.jpg`,
            name: `Will Smith`,
            message: `WTF dude!! absofuckingloutely.`,
            time: `13 Dec`,
            now: false,
            select: false,
        },
        {
            profileImage: `https://randomuser.me/api/portraits/men/22.jpg`,
            name: `Brad Pitt`,
            message: `you called Brad.`,
            time: `31 Dec`,
            now: false,
            select: false,
        },
        {
            profileImage: `https://randomuser.me/api/portraits/men/99.jpg`,
            name: `Tom Hanks`,
            message: `Tom called you.`,
            time: `31 Dec`,
            now: false,
            select: false,
        },
        {
            profileImage: `https://randomuser.me/api/portraits/men/41.jpg`,
            name: `Dwayne Johnson`,
            message: `How can i forget about that man!.`,
            time: `12 Nov`,
            now: false,
            select: false,
        },
        {
            profileImage: `https://randomuser.me/api/portraits/men/70.jpg`,
            name: `Johnny Depp`,
            message: `Alright! let's catchup tomorrow!.`,
            time: `4 Nov`,
            now: false,
            select: false,
        },
        {
            profileImage: `https://randomuser.me/api/portraits/men/20.jpg`,
            name: `Leonardo Dicaprio`,
            message: `How can you leave Rose dude. I hate you!`,
            time: `26 Oct`,
            now: false,
            select: false,
        },
        {
            profileImage: `https://randomuser.me/api/portraits/men/32.jpg`,
            name: `Tom Cruise`,
            message: `Happy birthday to you my friend!`,
            time: `2 Oct`,
            now: false,
            select: false,
        },
    ],
};
